# Generated by Django 5.1.4 on 2024-12-07 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='nombre',
            field=models.CharField(help_text='nombre empresa', max_length=100),
        ),
    ]
